name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          git \
          ffmpeg \
          libsdl2-dev \
          libsdl2-image-dev \
          libsdl2-mixer-dev \
          libsdl2-ttf-dev \
          libportmidi-dev \
          libswscale-dev \
          libavformat-dev \
          libavcodec-dev \
          zlib1g-dev \
          openjdk-17-jdk \
          autoconf \
          libtool \
          pkg-config \
          cmake \
          libffi-dev \
          libssl-dev \
          zip \
          unzip

    - name: Install Buildozer
      run: |
        pip install --upgrade pip
        pip install buildozer==1.5.0 cython==0.29.33

    - name: Remove old buildozer data
      run: |
        rm -rf ~/.buildozer
        rm -rf .buildozer

    - name: Build APK
      env:
        ANDROID_NDK_HOME: /usr/local/lib/android/sdk/ndk/27.3.13750724
      run: |
        buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: endless-runner-apk
        path: bin/*.apk